### ISSUE TITLE
latest .net support

### ISSUE THREAD

**Issue by TheEndHunter** [wwrd/ikvm8#15]
wondering if this project is gonna get an update to .net 5 or even just .net standard 2.1?

**Comment by ams-tschoening** [comment]
Just for info, such things have at least been discussed at various places already:

https://github.com/ikvm-revived/ikvm/issues/13
https://github.com/ikvm-revived/ikvm/issues/20
https://github.com/ikvm-revived/ikvm/issues/21
https://github.com/ikvm-revived/ikvm/pull/25#issuecomment-705608623

**Comment by TheEndHunter** [comment]
Oh ok, thanks. I'll have a read of them 🙂
