### ISSUE TITLE
System.MethodAccessException:“[IKVM.OpenJDK.Core.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations

### ISSUE THREAD

**Issue by CYDHJ** [wwrd/ikvm8#17]
Run build.framework.cmd  Build complete，No error，reference  ikvm.*.dll in my project Debug throw 

MethodAccessException:“[IKVM.OpenJDK.Core.dll] 

Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations

Please help me, thank you。

**Comment by ams-tschoening** [comment]
You have most likely built ikvm-revived and therefore should file the issue there:

https://github.com/ikvm-revived/ikvm

**Comment by CYDHJ** [comment]
Sorry, yes, I chose the wrong location。

**Comment by CYDHJ** [comment]
> 您很可能已经构建了 ikvm-revived，因此应该在此处提交问题：
> 
> https://github.com/ikvm-revived/ikvm

Can you help analyze and handle this exception?
