### ISSUE TITLE
How is it with the compatibility?

### ISSUE THREAD

**Issue by kosuodhmwa** [wwrd/ikvm8#18]
Is it now compatible to .NET version > 2.0 or, much more better, to the new "Core" versions?

Thank you very very much for your feedback(s)... :-)

With best regards, Jan

**Comment by kosuodhmwa** [comment]
I also asked this on similar projects -> https://github.com/jessielesbian/ikvm/issues/19

**Comment by ams-tschoening** [comment]
This has pretty much been asked before already: https://github.com/windward-studios/ikvm8/issues/15#issuecomment-757515666

**Comment by kosuodhmwa** [comment]
Oh, thank you very very much for your fast feedback!! :-)
